-- MySQL Script generated by MySQL Workbench
-- Fri May 30 10:11:41 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bt3php
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bt3php
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bt3php` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bt3php` ;

-- -----------------------------------------------------
-- Table `bt3php`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt3php`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `role` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bt3php`.`providers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt3php`.`providers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `tax_code` VARCHAR(15) NOT NULL,
  `des` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(50) NOT NULL,
  `address` VARCHAR(200) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  `website_url` VARCHAR(255) NOT NULL,
  `reputation` INT NULL DEFAULT NULL,
  `pay_account_number` VARCHAR(45) NOT NULL,
  `logo_url` VARCHAR(45) NOT NULL,
  `banner_url` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bt3php`.`services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt3php`.`services` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `des` VARCHAR(255) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `updated_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bt3php`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt3php`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `des` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(50) NOT NULL,
  `created_date` DATETIME NOT NULL,
  `provide_deadline` DATETIME NOT NULL,
  `paid_date` DATETIME NULL DEFAULT NULL,
  `currency` VARCHAR(15) NOT NULL,
  `vat` FLOAT NOT NULL,
  `user_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  `service_id` INT NOT NULL,
  `price` DECIMAL(18,2) NOT NULL,
  `unit` VARCHAR(45) NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_bill_users_idx` (`user_id` ASC),
  INDEX `fk_bills_providers1_idx` (`provider_id` ASC),
  INDEX `fk_orders_services1_idx` (`service_id` ASC),
  CONSTRAINT `FK_bill_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `bt3php`.`users` (`id`),
  CONSTRAINT `fk_bills_providers1`
    FOREIGN KEY (`provider_id`)
    REFERENCES `bt3php`.`providers` (`id`),
  CONSTRAINT `fk_orders_services1`
    FOREIGN KEY (`service_id`)
    REFERENCES `bt3php`.`services` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bt3php`.`contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt3php`.`contracts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(50) NOT NULL,
  `signed_date` DATETIME NOT NULL,
  `expire_date` DATETIME NOT NULL,
  `contract_url` VARCHAR(255) NOT NULL,
  `provider_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_contract_provider_idx` (`provider_id` ASC),
  CONSTRAINT `FK_contract_provider`
    FOREIGN KEY (`provider_id`)
    REFERENCES `bt3php`.`providers` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bt3php`.`provide_services`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bt3php`.`provide_services` (
  `service_id` INT NOT NULL,
  `provider_id` INT NOT NULL,
  `provide_price` DECIMAL(18,2) NOT NULL,
  `currency` VARCHAR(15) NOT NULL,
  `contract_id` INT NULL,
  PRIMARY KEY (`service_id`, `provider_id`),
  INDEX `FK_provideService_provide_idx` (`provider_id` ASC),
  INDEX `fk_provide_services_contracts1_idx` (`contract_id` ASC),
  CONSTRAINT `FK_provideService_provide`
    FOREIGN KEY (`provider_id`)
    REFERENCES `bt3php`.`providers` (`id`),
  CONSTRAINT `FK_provideService_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `bt3php`.`services` (`id`),
  CONSTRAINT `fk_provide_services_contracts1`
    FOREIGN KEY (`contract_id`)
    REFERENCES `bt3php`.`contracts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
